import {ArrowRight,Check,ChevronLeft,ChevronRight,CirclePlay,Globe2,PackageCheck,Scissors,ShieldCheck,Truck,Users} from 'lucide-react'
import Nav from './components/Nav'
import {BuiltToFight,CustomerPaths,EditorialCategories,GlobalPromise} from './components/HomeExperience'
import {products} from './data'
import {Link} from './routing'

const featuredSlugs=['fight-short','elite-fight-shorts','shadow-series','reign-fight-shorts']
const featured=featuredSlugs
  .map(slug=>products.find(product=>product.slug===slug))
  .filter((product):product is NonNullable<typeof product>=>Boolean(product))
  .map(product=>({
    name:product.name,
    price:product.price,
    status:product.tag,
    image:product.image,
    slug:product.slug,
  }))
const process=['Lead','Customization','Sample','Quote','Design approval','Payment','Manufacturing','Quality control','Shipping','Reorder']

export default function StorefrontHome(){return <><Nav/><main className="reference-home" id="top">
 <section className="ref-hero"><img src="/images/hero-fighter.webp" alt="Combat athlete wearing black fight shorts in a dark arena"/><div className="ref-hero-shade"/><div className="ref-hero-copy"><h1>FIGHTWEAR<br/>BUILDS<br/><em>BIGGER</em><br/><em>STORIES</em></h1><p>Custom fightwear for athletes, gyms and global brands.</p><div><Link className="ref-btn red" to="/shop">SHOP NOW</Link><Link className="ref-btn outline" to="/customize">CUSTOMIZE YOUR GEAR</Link></div></div><div className="hero-side"><h2>MORE<br/>THAN GEAR.<br/>A STRONGER<br/>TOMORROW.</h2><Link to="/#story"><CirclePlay/> WATCH OUR STORY</Link></div><div className="hero-benefits"><span><ShieldCheck/><b>PREMIUM QUALITY<br/>FIGHTWEAR</b></span><span><PackageCheck/><b>LOW MOQ<br/>FOR GYMS & BRANDS</b></span><span><Globe2/><b>GLOBAL SHIPPING</b></span><span><Users/><b>TRUSTED BY<br/>FIGHT COMMUNITIES</b></span></div></section>
 <CustomerPaths/>
 <section className="ref-shop" id="shop"><div className="ref-section-head"><div><h2>SHOP FIGHTWEAR</h2><p>Full PRD catalog foundations — custom apparel, protective gear and academy programs.</p></div><Link to="/shop">VIEW ALL <ArrowRight/></Link></div><div className="pill-row"><Link className="active" to="/shop">All</Link><Link to="/shop?category=GIs">Jiu Jitsu Gis</Link><Link to="/shop?category=Rash%20Guards">Rash Guards</Link><Link to="/shop?category=Fight%20Shorts">Grappling Shorts</Link><Link to="/shop?category=Spats">Spats</Link><Link to="/shop?category=Gloves">Gloves</Link><Link to="/shop?category=Bags">Bags</Link><Link to="/shop?custom=true">Customize</Link><Link to="/shop?wholesale=true">Wholesale</Link></div><div className="ref-products">{featured.map(product=><article key={product.slug}><Link className="ref-product-image" to={`/product/${product.slug}`}><img src={product.image} alt={product.name} loading="lazy"/></Link><h3>{product.name}</h3><b>{product.price}</b><div className="rating"><span>{product.status}</span></div></article>)}</div></section>
 <BuiltToFight/>
 <EditorialCategories/>
 <div className="ref-program-grid"><section className="program-card academy-card" id="academy"><img src="/images/academy-team.webp" alt="Combat sports academy team in a training gym" loading="lazy"/><div className="program-shade"/><div className="program-copy"><h2>GYM & ACADEMY<br/>PROGRAM</h2><p>Custom gear. Stronger teams. Greater opportunities.</p><ul><li><Check/>Wholesale pricing</li><li><Check/>Free digital mockups</li><li><Check/>Physical samples</li><li><Check/>Academy store setup</li><li><Check/>Dedicated support</li></ul><div><Link className="ref-btn red" to="/request-mockup?intent=academy">APPLY FOR WHOLESALE</Link><Link className="ref-btn outline" to="/academy">EXPLORE PROGRAM</Link></div></div></section><section className="program-card label-card" id="private"><img src="/images/private-label.webp" alt="Close-up of premium technical fightwear fabric and label" loading="lazy"/><div className="program-shade"/><div className="program-copy"><h2>PRIVATE LABEL<br/>MANUFACTURING</h2><p>Bring your fightwear brand to life. We handle manufacturing, you own the brand.</p><ul><li><Check/>Custom designs & materials</li><li><Check/>Low MOQ</li><li><Check/>Custom labels & packaging</li><li><Check/>Full production support</li><li><Check/>Global shipping</li></ul><Link className="ref-btn red" to="/request-mockup?intent=private-label">START YOUR BRAND</Link></div></section></div>
 <div className="ref-info-grid"><section className="ref-process" id="process"><div className="ref-section-head"><div><h2>OUR PROCESS</h2><p>From your idea to the global stage.</p></div></div><div className="ref-process-line">{process.map((item,i)=><div key={item}><i>{i===1?<Scissors/>:i===7?<ShieldCheck/>:i===8?<Truck/>:<PackageCheck/>}</i><b>{i+1}</b><strong>{item}</strong><small>{['Get in touch','Design your gear','Approve quality','Transparent pricing','Final confirmation','Deposit & balance','We bring it to life','Checked for excellence','Worldwide delivery','Easier next time'][i]}</small></div>)}</div><Link className="ref-btn light-outline" to="/process">LEARN MORE ABOUT OUR PROCESS</Link></section><section className="ref-track"><div className="ref-section-head"><div><h2>TRACK YOUR ORDER</h2><p>Stay updated at every step.</p></div></div><div className="mini-track"><span className="done"><Check/><b>Order<br/>Placed</b><small>DEMO</small></span><span className="done"><Check/><b>Design<br/>Approved</b><small>DEMO</small></span><span className="current"><PackageCheck/><b>In<br/>Production</b><small>DEMO</small></span><span><ShieldCheck/><b>Quality<br/>Control</b></span><span><Truck/><b>Shipping</b></span></div><div className="track-order-card"><img src="/images/products/fight-short-1.png" alt="Custom fight shorts"/><div><b>Custom Fight Shorts</b><p>Demo order SF-2026-0148</p><em>Demo stage</em><small>Open the tracker to explore a clearly labeled sample timeline.</small></div></div><div className="track-links"><Link to="/track">VIEW DEMO</Link><Link to="/request-mockup?intent=support">MESSAGE SUPPORT</Link></div></section></div>
 <section className="ref-testimonial" id="story"><img src="/images/academy-team.webp" alt="Combat athletes training together" loading="lazy"/><div className="program-shade"/><div className="testimonial-title"><h2>TRUSTED BY<br/>FIGHT COMMUNITIES<br/>WORLDWIDE</h2><p>Verified athlete, academy and brand stories will be added only after approval.</p><Link className="ref-btn outline" to="/about">ABOUT SKAWA</Link></div><div className="testimonial-quote"><ChevronLeft aria-hidden="true"/><div><blockquote>Customer stories are intentionally withheld until SKAWA supplies verified testimonials.</blockquote><p>Evidence-first content<br/><small>No invented clients, quotes or ratings</small></p></div><ChevronRight aria-hidden="true"/></div></section>
 <GlobalPromise/>
 </main><footer className="ref-footer" id="about"><div className="logo"><span>SKAWA</span><b>FIGHT</b></div><p>Custom Fightwear. Stronger Together.</p><nav><Link to="/shop">Shop</Link><Link to="/academy">Gym & Academy</Link><Link to="/private-label">Private Label</Link><Link to="/process">Our Process</Link><Link to="/selected-fightwear">Selected Fightwear</Link><Link to="/sample-kit">Sample Kit</Link><Link to="/about">About</Link><Link to="/request-mockup">Contact</Link></nav><small>© 2026 SKAWA FIGHT</small></footer></>}
